version: '3.8'
services:
  ingestion:
    build: ./ingestion
    container_name: ingestion
    restart: unless-stopped
    volumes:
      - ./ingestion:/app
    networks:
      - ml-pipeline

  data-streaming:
    build: ./data/streaming
    container_name: streaming
    volumes:
      - ./data/streaming:/app
    networks:
      - ml-pipeline


networks:
  ml-pipeline:
    driver: bridge
